GET http://localhost:5186/games

###
GET http://localhost:5186/games/3

###
POST http://localhost:5186/games
Content-Type: application/json

{
    "name":"Minecraft",
    "Genre":"Kids and Family",
    "price":19.99,
    "ReleaseDate":"2011-11-18"
}

###
PUT http://localhost:5186/games/1
Content-Type: application/json

{
    "name": "Assassin's Creed Valhalla",
    "genre": "Adventure",
    "price": 39.99,
    "releaseDate": "2010-05-22"
}